routes/web.php
<?php

use App\Imports\KelolaData\Inflow\InflowImport;
use App\Imports\KelolaData\Outflow\OutFlowImport;
use App\Imports\KelolaData\Uyd\UydImport;
use App\Imports\KelolaData\UydPecahan\UydPecahanImport;
use Maatwebsite\Excel\Facades\Excel;
use Spatie\Browsershot\Browsershot;

Route::middleware('auth')->group(function() {
	Route::get('/', function () {
	    return redirect()->route('dashboard');
	    // return view('welcome');
	});
	Route::get('/register', function () {
	    return redirect()->route('dashboard');
	    // return view('welcome');
	});

	
	Route::get('/dashboard', 'Dashboard\DashboardController@index')->name('dashboard');	

	Route::name('master.')->prefix('master')->namespace('Master')->group(function() {
		Route::post('/event/grid', 'EventController@grid')->name('event.grid');
		Route::resource('/event', 'EventController');
	});


	Route::name('setting.')->prefix('setting')->namespace('Setting')->group( function() {
		Route::get('/', function(){
			return redirect()->route('setting.users.index');
		});

		Route::post('users/grid', 'UserController@grid')->name('users.grid');
		Route::resource('users', 'UserController');

		Route::post('roles/grid', 'RoleController@grid')->name('roles.grid');
		Route::resource('roles', 'RoleController');
	});

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Setting/RoleController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\Facades\DataTables;

use App\Models\Auth\Role;

class RoleController extends Controller
{
    protected $routes = 'setting.roles';

    function __construct()
    {
        $this->setRoutes($this->routes);
        // Header Grid Datatable
        $this->setTableStruct([
            [
                'data' => 'num',
                'name' => 'num',
                'label' => '#',
                'orderable' => false,
                'searchable' => false,
                'className' => 'text-center',
                'width' => '20px',
            ],
            /* --------------------------- */
            [
                'data' => 'name',
                'name' => 'name',
                'label' => 'Name',
                'sortable' => true,
            ],
            [
                'data' => 'users',
                'name' => 'users',
                'label' => 'User Assigned',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'perms',
                'name' => 'perms',
                'label' => 'Permissions',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'created_at',
                'name' => 'created_at',
                'label' => 'Created At',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'updated_at',
                'name' => 'updated_at',
                'label' => 'Updated At',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'action',
                'name' => 'action',
                'label' => 'Aksi',
                'searchable' => false,
                'sortable' => false,
                'width' => '90px',
                'className' => 'text-center'
            ]
        ]);
    }

    public function grid()
    {
        $records = Role::when($name = request()->name, function($q) use ($name) {
                            $q->where('name', 'like', '%'.$name.'%');
                        })
                        ->select('*');
        $routes = $this->routes;

        return DataTables::of($records)
               ->addColumn('num', function($record) {
                    return request()->start;
               })
               ->addColumn('perms', function($record) {
                    return $record->permissions->count().' Permissions';
               })
               ->addColumn('users', function($record) {
                    return $record->users->count().' Users';
               })
               ->editColumn('created_at', function($record){
                    return $record->created_at->diffForHumans();
               })
               ->editColumn('updated_at', function($record){
                    return $record->updated_at->diffForHumans();
               })
               ->addColumn('action', function($record) use ($routes) {
                    $buttons = '';

                    $buttons .= $this->makeButton([
                        'type'    => 'url',
                        'class'   => $record->isSuperAdmin() ? '' : 'm-r',
                        'label'   => '<i class="fa fa-check-square text-success"></i>',
                        'tooltip' => 'Assign Permissions',
                        'url'  => route($routes.'.show', $record->id),
                    ]);

                    if(!$record->isSuperAdmin()){
                        $buttons .= $this->makeButton([
                            'type' => 'edit',
                            'id'   => $record->id,
                        ]);

                        $buttons .= $this->makeButton([
                            'type' => 'delete',
                            'id'   => $record->id,
                        ]);
                    }

                    return $buttons;
               })
               ->make(true);
    }

    public function index()
    {
        return $this->render('settings.role.index');
    }

    public function create()
    {
        return $this->render('settings.role.create');
    }

    public function store()
    {
        return Role::create(request(['name']));
    }

    public function show(Role $role)
    {
        $perms = [
            'Home' => [
                'home' => ['read'],
            ],
            
            // Dashboard
            'Dashboard' => [
                'dashboard pkse'        => ['read'],
                'dashboard kecukupan'   => ['read'],
                'dashboard titipan'     => ['read'],
                'dashboard outflow'     => ['read'],
                'dashboard inflow'      => ['read'],
                'dashboard pemusnahan'  => ['read'],
                'dashboard khazanah'    => ['read'],
                'dashboard backlog'     => ['read'],
                'dashboard remise'      => ['read'],
                'dashboard keliling'    => ['read'],
                'dashboard msuk'        => ['read'],
                'dashboard uyd'         => ['read'],
                'dashboard survei'         => ['read'],
            ],

            // Data
            'Data' => [
                'data posisikas'   => ['create', 'read', 'update', 'delete'],
                'data outflow'     => ['create', 'read', 'update', 'delete'],
                'data inflow'      => ['create', 'read', 'update', 'delete'],
                'data pemusnahan'  => ['create', 'read', 'update', 'delete'],
                'data uyd'         => ['create', 'read', 'update', 'delete'],
                'data uyd pecahan' => ['create', 'read', 'update', 'delete'],
                'data proyeksi'    => ['create', 'read', 'update', 'delete'],
                'data survei'      => ['create', 'read', 'update', 'delete'],
                'data remise'      => ['create', 'read', 'update', 'delete'],
            ],

            // Master
            'Master' => [
                'master pecahan'   => ['create', 'read', 'update', 'delete'],
                'master kdk'       => ['create', 'read', 'update', 'delete'],
                'master rekening'  => ['create', 'read', 'update', 'delete'],
                'master satker'    => ['create', 'read', 'update', 'delete'],
                'master kapasitas' => ['create', 'read', 'update', 'delete'],
                'master plafond'   => ['create', 'read', 'update', 'delete'],
            ],

            // Setting
            'Setting' => [
                'setting user'      => ['create', 'read', 'update', 'delete'],
                'setting role'      => ['create', 'read', 'update', 'delete']
            ]
        ];

        return $this->render('settings.role.detail', ['record' => $role, 'perms' => $perms]);
    }

    public function edit(Role $role)
    {
        return $this->render('settings.role.edit', ['record' => $role]);
    }

    public function update(Role $role)
    {
        $role->update(request(['name']));

        if($perms = request()->perms){
            app()->make(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();

            $role->syncPermissions(array_keys($perms));
            // dd(array_keys($perms));
        }

        return $role;
    }

    public function destroy(Role $role)
    {
        $role->delete();

        return response()->json([
            'success' => true
        ]);
    }

}

app/Http/Controllers/Setting/UserController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\Facades\DataTables;

use App\Http\Requests\Setting\UserRequest;
use App\Models\Auth\User;

class UserController extends Controller
{
    protected $routes = 'setting.users';

    function __construct()
    {
        $this->setRoutes($this->routes);
        // Header Grid Datatable
        $this->setTableStruct([
            [
                'data' => 'num',
                'name' => 'num',
                'label' => '#',
                'orderable' => false,
                'searchable' => false,
                'className' => 'text-center',
                'width' => '20px',
            ],
            /* --------------------------- */
            [
                'data' => 'name',
                'name' => 'name',
                'label' => 'Name',
                'sortable' => true,
            ],
            [
                'data' => 'email',
                'name' => 'email',
                'label' => 'Email',
                'sortable' => true,
            ],
            [
                'data' => 'role',
                'name' => 'role',
                'label' => 'Role',
                'sortable' => true,
            ],
            [
                'data' => 'created_at',
                'name' => 'created_at',
                'label' => 'Created At',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'updated_at',
                'name' => 'updated_at',
                'label' => 'Updated At',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'action',
                'name' => 'action',
                'label' => 'Aksi',
                'searchable' => false,
                'sortable' => false,
                'width' => '80px',
                'className' => 'text-center'
            ]
        ]);
    }

    public function grid()
    {
        $records = User::when($name = request()->name, function($q) use ($name) {
                            $q->where('name', 'like', '%'.$name.'%');
                        })
                        ->when($email = request()->email, function($q) use ($email) {
                            $q->where('email', 'like', '%'.$email.'%');
                        })
                        ->select('*');

        return DataTables::of($records)
               ->addColumn('num', function($record) {
                    return request()->start;
               })
               ->addColumn('role', function($record) {
                    return $record->roles->first()
                         ? $record->roles->first()->name
                         : '-';
               })
               ->editColumn('created_at', function($record){
                    return $record->created_at->diffForHumans();
               })
               ->editColumn('updated_at', function($record){
                    return $record->updated_at->diffForHumans();
               })
               ->addColumn('action', function($record) {
                    $buttons = '';

                    $buttons .= $this->makeButton([
                        'type' => 'edit',
                        'id'   => $record->id,
                    ]);
                    if($record->id !== auth()->user()->id){
                        $buttons .= $this->makeButton([
                            'type' => 'delete',
                            'id'   => $record->id,
                        ]);
                    }

                    return $buttons;
               })
               ->make(true);
    }

    public function index()
    {
        return $this->render('settings.user.index');
    }

    public function create()
    {
        return $this->render('settings.user.create');
    }

    public function store(UserRequest $request)
    {
        $user = User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);

        $user->assignRole($request->role);

        return $user;
    }

    public function show(User $user)
    {
        return $user->toJson();
    }

    public function edit(User $user)
    {
        return $this->render('settings.user.edit', ['record' => $user]);
    }

    public function update(UserRequest $request, User $user)
    {
        $attrs = [
            'name' => $request['name'],
            'email' => $request['email'],
        ];
        
        if($pass = $request->password){
            $attrs['password'] = Hash::make($pass);
        }

        $user->update($attrs);
        $user->assignRole($request->role);

        return $user;
    }

    public function destroy(User $user)
    {
        $user->delete();

        return response()->json([
            'success' => true
        ]);
    }

}

resources/views/settings/role/create.blade.php
<form action="{{ route($routes.'.store') }}" method="POST" id="formData">
    @csrf

    <div class="modal-header">
        <h3 class="modal-title">Add New Role</h3>
    </div>
    <div class="modal-body">
        {{-- <p class="text-muted">Please fill the information to continue</p> --}}
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" name="name" class="form-control" placeholder="Enter role name" required="">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary save button">Save</button>
    </div>

    <div class="loading dimmer padder-v">
        <div class="loader"></div>
    </div>
</form>

resources/views/settings/role/detail.blade.php
@extends('layouts.base')

@include('libs.actions')

@section('title', 'SETTING - ROLE MANAGEMENT')

@section('side-header')
    <div class="btn-group">
        <a href="{{ route('setting.users.index') }}" type="button" class="btn btn-default">User Management</a>
        <a href="{{ route('setting.roles.index') }}" type="button" class="btn btn-primary">Role Management</a>
    </div>
@endsection

@section('body')
	<form id="formData" action="{{ route($routes.'.update', $record->id) }}" method="POST">
		@method('PATCH')
		@csrf
		
		<input type="hidden" name="name" value="{{ $record->name }}">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="font-thin h4">
					<span>Role : {{ $record->name }}</span>
					<span class="pull-right">{{ $record->users->count() }} Users</span>
				</h4>
			</div>
			<table class="table table-striped b-t b-light">
				<thead>
					<tr>
						<th class="text-center">Features</th>
						<th class="text-center">Read</th>
						<th class="text-center">Create</th>
						<th class="text-center">Update</th>
						<th class="text-center">Delete</th>
						<th class="text-center"></th>
					</tr>
				</thead>
				@foreach($perms as $title => $group)
					<thead>
						<tr>
							<th>{{ $title }}</th>
							<th class="text-center">
								<button type="button" class="btn btn-default btn-addon btn-sm check all" data-check="read">
									<i class="fa fa-check"></i>Read All
								</button>
							</th>
							<th class="text-center">
								<button type="button" class="btn btn-default btn-addon btn-sm check all" data-check="create">
									<i class="fa fa-check"></i>Create All
								</button>
							</th>
							<th class="text-center">
								<button type="button" class="btn btn-default btn-addon btn-sm check all" data-check="update">
									<i class="fa fa-check"></i>Update All
								</button>
							</th>
							<th class="text-center">
								<button type="button" class="btn btn-default btn-addon btn-sm check all" data-check="delete">
									<i class="fa fa-check"></i>Delete All
								</button>
							</th>
							<th class="text-center">
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach($group as $key => $perm)
							<tr>
								<td>{{ ucwords(str_replace(['-', '_'], ' ', $key)) }}</td>
								<td class="text-center">
									@if(in_array('read', $perm))
									<label class="i-checks m-b-none">
										<input type="checkbox" class="read check" name="perms[read {{$key}}]" value="1" @if($record->hasPermissionTo('read '.$key)) checked @endif><i></i>
									</label>
									@endif
								</td>
								<td class="text-center">
									@if(in_array('create', $perm))
									<label class="i-checks m-b-none">
										<input type="checkbox" class="create check" name="perms[create {{$key}}]" value="1" @if($record->hasPermissionTo('create '.$key)) checked @endif><i></i>
									</label>
									@endif
								</td>
								<td class="text-center">
									@if(in_array('update', $perm))
									<label class="i-checks m-b-none">
										<input type="checkbox" class="update check" name="perms[update {{$key}}]" value="1" @if($record->hasPermissionTo('update '.$key)) checked @endif><i></i>
									</label>
									@endif
								</td>
								<td class="text-center">
									@if(in_array('delete', $perm))
									<label class="i-checks m-b-none">
										<input type="checkbox" class="delete check" name="perms[delete {{$key}}]" value="1" @if($record->hasPermissionTo('delete '.$key)) checked @endif><i></i>
									</label>
									@endif
								</td>
								<td class="text-center">
									<button type="button" class="btn btn-default btn-addon btn-sm select all"><i class="fa fa-check"></i>Select All</button>
								</td>
							</tr>
						@endforeach
					</tbody>
				@endforeach
			</table>
			<div class="panel-footer">
				<a href="{{ url()->previous() }}" class="btn btn-sm btn-default btn-addon">
					<i class="fa fa-angle-left"></i> Back
				</a>
				<button type="button" class="btn btn-sm btn-success btn-addon pull-right save button">
					<i class="fa fa-save"></i> Save
				</button>
			</div>
		</div>
	    <div class="loading dimmer padder-v" style="display: none">
	        <div class="loader"></div>
	    </div>
	</form>
@endsection

@push('scripts')
<script>
	$(document).on('click', '.select.all', function(e){
		var container = $(this).closest('tr');
		var checks = container.find('.check');

		checks.prop('checked', !checks.prop('checked'));
	});

	$(document).on('click', '.check.all', function(e){
		var container = $(this).closest('thead').next('tbody');
		var target = $(this).data('check');
		var checks = container.find('.' + target + '.check');

		checks.prop('checked', !checks.prop('checked'));
	});

    $(document).on('click', '.save.button', function(e){
        saveData('formData', function(resp){
            location.href = "{{ route($routes.'.index') }}";
        });
    });
</script>
@endpush

resources/views/settings/role/edit.blade.php
<form action="{{ route($routes.'.update', $record->id) }}" method="POST" id="formData">
    @method('PATCH')
    @csrf
    <input type="hidden" name="id" value="{{ $record->id }}">

    <div class="modal-header">
        <h3 class="modal-title">Edit Role</h3>
    </div>
    <div class="modal-body">
        {{-- <p class="text-muted">Please fill the information to continue</p> --}}
        <div class="form-group">
            <label class="control-label">Name</label>
            <input type="text" name="name" class="form-control" placeholder="Enter role name" value="{{ $record->name }}" required>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary save button">Save</button>
    </div>

    <div class="loading dimmer padder-v">
        <div class="loader"></div>
    </div>
</form>

resources/views/settings/role/index.blade.php
@extends('layouts.list')

@section('title', 'Setting - Role Management')

@section('side-header')
    <div class="btn-group">
        <a href="{{ route('setting.users.index') }}" type="button" class="btn btn-default">User Management</a>
        <a href="{{ route('setting.roles.index') }}" type="button" class="btn btn-primary">Role Management</a>
    </div>
@endsection

@section('filters')
    <div class="form-group">
        <label class="control-label m-r-sm" for="filters"><i class="fa fa-filter"></i> &nbsp; Filter</label>
        <label class="control-label sr-only" for="filter-name">Name</label>
        <input type="text" class="form-control filter-control" name="filter[name]" data-post="name" placeholder="Name Contain">
    </div>
@endsection